### ISSUE TITLE
WRONG README

### ISSUE THREAD

**Issue by Kyori-kyo** [victormicco/victormiccodev#3]
<img width="1001" alt="image" src="https://github.com/user-attachments/assets/ec4236ea-9ae6-4650-bf71-66b3081dcdca">

The readme its about a portfolio boilerplate, not yours
so its confusing to read about a guy's portfolio boilerplate while seeing your portfolio

**Comment by victormicco** [comment]
here in brazil we call it creditos

**Comment by Kyori-kyo** [comment]
creditos != from making your readme the same as his, your pombo
thats just lazyness
as japa once said "theres no carpet unpooped that you cant poop in it again, but with your poop".
